puts "Coding is fun!!!"
puts "I am very tired"
puts "I'm also quite stressed because I have an exam tomorrow and a lot of projects due today that I haven't finished"
puts "I'm also fAmIShEd and I want some of those raspberry cookies :(((("
puts "I'm happy that I'm actually understanding what I'm doing for once"
puts "I feel sad because I keep not doing things that I want to do and then I regret it later :( the football game was fun I guess I just wish we won"